# Project information

site_name: Secrets Manager Builder Sessions
site_description: 'A collection of hands-on Builder Sesssions to learn about using Secrets Manager.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://secrets-manager.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-secretsmgr-workshop'
repo_url: 'https://github.com/aws-samples/aws-secretsmgr-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - 'RDS and Fargate':
    - 'Scenario': 'RDSFargate/index.md'
    - 'Getting started': 'RDSFargate/getting-started.md'
    - 'Build phase': 'RDSFargate/build.md'
    - 'RDS phase': 'RDSFargate/RDS.md'
    - 'Fargate phase': 'RDSFargate/Fargate.md'
    - 'Clean up phase': 'RDSFargate/cleanup.md'
  - 'Contributing': 'contribute.md'
  - 'License': 'https://github.com/aws-samples/aws-secretsmgr-workshop/blob/master/LICENSE'
